In [2]:
#1. 길이가 10인 0-벡터를 만드세요.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
#2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.
np.eye(1,10,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [3]:
#3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#4. 위(3번) 벡터의 순서를 바꾸세요.
x=np.arange(10,50)
x=x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [5]:
#5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.


In [8]:
#7. 3x3 단위 행렬(identity matrix)을 만드세요
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#8. 난수 원소를 가지는 3x3 행렬을 만드세요
x=np.random.rand(3,3)
x                  

array([[0.5281639 , 0.78174002, 0.6520434 ],
       [0.82044129, 0.62902322, 0.19499474],
       [0.42425981, 0.10958729, 0.78759188]])

In [50]:
#9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

np.max(x)



0.8204412869383446

In [49]:
np.min(x)


0.10958729251394039

In [54]:
#10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.
np.mean(x,axis=1)

array([0.65398244, 0.54815308, 0.44047966])

In [55]:
np.mean(x,axis=0)

array([0.590955  , 0.50678351, 0.54487667])